### ISSUE TITLE
No default VPC for this user

### ISSUE THREAD

**Issue by accounts4vikas** [joaquincasares/cassandralauncher#17]
My company EC2 account does not have a default VPC and look like these script expect a default VPC to be present as I am getting "No default VPC for this user" error while running the script. 

Is there any version in progress to allow specifying the VPC in the configuration?

Error Message - 
****************************************************************************************
Starting an EC2 cluster of type m1.large with image ami-05caca6c...
Ensuring vsangwan-keypair20150203 pem key exists on AWS...
Ensuring vsangwan-keypair20150203 pem key exists on filesystem...
Ensuring vsangwan-keypair20150203 pem key's permissions are acceptable...
Traceback (most recent call last):
  File "/Users/vsangwan/anaconda/bin/cassandralauncher", line 4, in <module>
    cassandralauncher.CassandraLauncher()
  File "/Users/vsangwan/anaconda/lib/python2.7/site-packages/cassandralauncher/__init__.py", line 6, in __init__
    cassandralauncher.run()
  File "/Users/vsangwan/anaconda/lib/python2.7/site-packages/cassandralauncher/cassandralauncher.py", line 751, in run
    main()
  File "/Users/vsangwan/anaconda/lib/python2.7/site-packages/cassandralauncher/cassandralauncher.py", line 675, in main
    check_cascading_options('security_public_inbound_source', optional=True))
  File "/Users/vsangwan/anaconda/lib/python2.7/site-packages/cassandralauncher/ec2.py", line 150, in create_cluster
    ds_security_group = conn.create_security_group('DataStax', 'Security group for running DataStax products')
  File "/Users/vsangwan/anaconda/lib/python2.7/site-packages/boto/ec2/connection.py", line 3003, in create_security_group
    SecurityGroup, verb='POST')
  File "/Users/vsangwan/anaconda/lib/python2.7/site-packages/boto/connection.py", line 1207, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>VPCIdNotSpecified</Code><Message>No default VPC for this user</Message></Error></Errors><RequestID>c725df67-ec48-48e5-9ff5-41f8e83c71f4</RequestID></Response>
vsangwan-mbp15:~ vsangwan$ vi .clusterlauncher.conf

**Comment by joaquincasares** [comment]
No sorry, there are no planned features going into this project.

Feel free to create a new option to specify your VPC Id, or feel free to hardcode it in ec2.py (this project uses boto which is heavily documented). If you do the former, I'd be happy to accept a pull request for the rest of the community.

Thanks!
